# Generated by Django 3.1.5 on 2021-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Best_Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('mfr', models.CharField(max_length=5000)),
                ('price', models.FloatField()),
                ('offer', models.IntegerField()),
                ('offer_price', models.FloatField()),
            ],
        ),
    ]
