# Generated by Django 3.1.5 on 2021-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthocare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
